version: '3'
services:
  task6-node:
    image: malagor/node
    build: .
    ports:
    - ${PORT}:${PORT}
    depends_on:
      - task6-postgres
    environment:
      - PORT=${PORT}
      - TZ=${TIME_ZONE}
    restart: always
    volumes:
    - ./logs:/usr/src/app/src/logs
    - ./src:/usr/src/app/src
  task6-postgres:
    image: malagor/postrges
    build:
      ./database/
    restart: always
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - postgresdb:/data/db
volumes:
  postgresdb:
