version: '3'
services:
  task6-node:
    image: malagor/node
    build: .
    command: npm run start
    ports:
    - ${PORT}:${PORT}
    depends_on:
      - task6-postgres
    environment:
      - PORT=${PORT}
      - TZ=${TIME_ZONE}
      - POSTGRES_HOST=task6-postgres
    restart: always
    volumes:
    - ./logs:/usr/src/app/src/logs
    - ./src:/usr/src/app/src
    networks:
       - malagor-net
  task6-postgres:
    image: malagor/postgres
    build:
      ./database/
    networks:
      - malagor-net
    restart: always
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
    - ./database/data:${PGDATA}
networks:
  malagor-net:
    driver: bridge
